spring:
  datasource:
    url: jdbc:mysql://mysql:3306/squadfit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: squadfit
    password: squadfit_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create   # 운영 전환 시엔 validate나 none 권장
  sql:
    init:
      mode: never
logging.level:
  org.hibernate.SQL: debug
