spring:
  datasource:
    url: jdbc:mysql://localhost:3307/squadfit?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: jaewoo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create   # 운영 전환 시엔 validate나 none 권장
  sql:
    init:
      mode: never
logging.level:
  org.hibernate.SQL: debug

# todo: 보완관련 처리하기
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
# 톰캣 메트릭
server:
  tomcat:
    mbeanregistry:
      enabled: true

#  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
#  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6