spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db/squadfit
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

# todo: 보완관련 처리하기
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
# 톰캣 메트릭
server:
  tomcat:
    mbeanregistry:
      enabled: true
file:
  # 최종 저장 위치
  upload-dir: C:/Users/USER/Desktop/squadfit/video
  # 청크 임시 저장 위치 (없으면 upload-dir 아래에 자동 생성)
  temp-dir: C:/Users/USER/Desktop/squadfit/video_tmp
  # 기본 청크 크기(바이트) - 클라이언트에게 안내용
  default-chunk-size: 5242880  # 5MB


#  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
#  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6